# Generated by Django 4.1.7 on 2023-09-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='current_hours',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='full_hours',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='longitude',
        ),
    ]
