# Generated by Django 4.1.7 on 2023-09-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_map', '0002_remove_brewery_current_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='e_rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='brewery',
            name='knownfor',
            field=models.CharField(default='unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='brewery',
            name='neighborhood',
            field=models.CharField(default='West Loop', max_length=100),
        ),
        migrations.AddField(
            model_name='brewery',
            name='patio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brewery',
            name='s_rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
