# Generated by Django 4.1.7 on 2023-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_map', '0003_brewery_e_rating_brewery_knownfor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='yelp',
            field=models.URLField(default='https://www.yelp.com/'),
        ),
    ]
