# Generated by Django 4.1.7 on 2023-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_map', '0005_brewery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='category',
            field=models.CharField(choices=[('cafe', 'Coffee Shop'), ('lunch', 'Lunch'), ('drinks', 'Drinks'), ('fine dining', 'Fine Dining'), ('cool', 'Cool Spot'), ('pub', 'Pub'), ('brewery', 'Brewery')], default='undefined', max_length=20),
        ),
    ]
