# Generated by Django 4.1.7 on 2023-10-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewery_map', '0016_alter_brewery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='category',
            field=models.CharField(choices=[('Cafe', 'Cafe'), ('Breakfast', 'Breakfast'), ('Nightlife', 'Nightlife'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Pub/Brewery', 'Pub/Brewery'), ('Brunch', 'Brunch')], default='undefined', max_length=20),
        ),
    ]
